DEBUG = False

# read input
with open('input.txt', 'r') as f:
    commands = f.read().splitlines()
    commands = [command.split(' ') for command in commands]

# initialize the cycle and the value of the X register
cycle = 1
value = 1

# initialize the string for the message generated by the program
image = ""

# loop over the commands
for instruction in commands:

    if DEBUG:
        print('cycle:', cycle, "\t", 'image generated:', image, "\n")

    # if we finished the pixels on the CRT
    if (cycle - 1) % 40 == 0:
        # add a new line to the image
        image += "\n"

    # add '#' to the image if the cycle - 1 is present in the sprite or ' ' otherwise
    if DEBUG:
        print("cycle-1", cycle-1, " sprite:", value-1, value, value+1,
              " is present? ", (cycle - 1) % 40 in (value - 1, value, value + 1))

    if (cycle - 1) % 40 in (value - 1, value, value + 1):
        image += "#"
    else:
        image += " "
    # which is the same as:
    # image += "#" if (cycle - 1) % 40 in (value - 1, value, value + 1) else " "

    if DEBUG:
        print('instruction:', instruction)

    # if the command is 'addx'
    if instruction[0] == 'addx':

        # if we finished the pixels on the CRT
        if cycle % 40 == 0:
            # add a new line to the image
            image += "\n"

        # add '#' to the image if the cycle is present in the sprite or ' ' otherwise
        if DEBUG:
            print("cycle", cycle, " sprite:", value - 1, value, value + 1,
                  " is present? ", (cycle) % 40 in (value - 1, value, value + 1))

        if (cycle) % 40 in (value - 1, value, value + 1):
            image += "#"
        else:
            image += " "
        # which is the same as:
        # image += "#" if (cycle - 1) % 40 in (value - 1, value, value + 1) else " "

        # update the value of the cycle
        cycle += 2

        # update the value of the X register
        value += int(instruction[1])

    # if the command is 'noop'
    elif instruction[0] == 'noop':
        # update the value of the cycle
        cycle += 1

# print the answer
print(image)
